### ISSUE TITLE
Freezes game when dropping all matching slots while using magnet from Sticky Fingers

### ISSUE THREAD

**Issue by AlurienFlame** [TerminalMC/MoreMouseTweaks#2]
### Before you open a new issue;

- [X] **Have you verified that this is a bug or defect in this mod?**
- [X] **Have you checked whether the issue has already been reported?** If it has been,  consider adding more information to the existing issue instead.
- [X] **Have you determined the minimum set of instructions to reproduce the issue?** If the  problem only occurs with other mods installed, then you should attempt to narrow down  exactly which mods are causing it.

### Mod Version

1.0.0+1.21.4-beta.3

### Mod Loader

Fabric

### Minecraft Version

1.21.4

### Issue Description

When using this mod in conjunction with the magnet mod [Sticky Fingers](https://modrinth.com/mod/sticky-fingers), the game freezes permanently when the player is in survival mode and has a magnet active and tries to use the "drop all matching slots" feature from this mod while carrying more than a stack of the item they're dropping. Nothing is logged to the console when the freeze occurs.

Given that Sticky Fingers appears to cause items to be picked up _instantly_ when dropped, I suspect that what's happening here is that each item dropped is being picked up again before all items of the same type have been dropped, leading to them being detected as another item of the same type and dropped again, creating an infinite loop. That doesn't explain why there's no issue in creative mode, though.

### Expected Behavior

All items of type would be dropped, then immediately be picked up again.

### Log File (required)

```mcfunction
https://mclo.gs/N1LOXM8
```

**Comment by NotRyken** [comment]
Thanks for the report, however I am able to replicate this issue using the Vanilla `CTRL+Q` feature with only Sticky Fingers and Fabric API installed, indicating that it is unrelated to MoreMouseTweaks. Please check whether this is the same for you, and if so, report it to the author of Sticky Fingers instead.
